services:
  db:
    image: postgres:16-alpine
    container_name: zmp-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=truonghoang2004
      - POSTGRES_DB=ngoclam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ngoclam"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: arigaio/atlas:latest
    container_name: zmp-migrate
    env_file:
      - .env
    volumes:
      - ./atlas.hcl:/atlas.hcl
      - ./internal/infrastructure/database/migrations:/migrations
    command: >
      migrate apply --url "$DB_URL"
      --dir "file://migrations" 
    depends_on:
      db:
        condition: service_healthy

  app:
    iamge: truonghx/ngoclam-be:latest
    container_name: zmp-be
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - migrate
    env_file:
      - .env

volumes:
  postgres_data:
