version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ngoclam
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    build: .
    command: make migrate
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/ngoclam?sslmode=disable

  app:
    build: .
    depends_on:
      - migrate
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/ngoclam?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  db_data:
