version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: zmp-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=truonghoang2004
      - POSTGRES_DB=ngoclam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ngoclam"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: arigaio/atlas:latest
    container_name: zmp-migrate
    env_file:
      - .env
    volumes:
      - ./atlas.hcl:/atlas.hcl
      - ./internal/infrastructure/database/migrations:/migrations
    command: >
      migrate apply --url "$DB_URL"
      --dir "file://migrations" 
    depends_on:
      db:
        condition: service_healthy

  app:
    image: truonghx/ngoclam-be:latest
    container_name: zmp-be
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - migrate
    environment:
      - VIRTUAL_HOST=api.nhavuonngoclam.com
      - LETSENCRYPT_HOST=api.nhavuonngoclam.com
      - LETSENCRYPT_EMAIL=xuantruong.tn.1712@gmail.com

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh

volumes:
  postgres_data:
  certs:
  vhost.d:
  html:
  acme:
